# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Draw a number of offspring given a fitness value
#'
#' The number of offspring is drawn in a Poisson distribution in
#' `rpois(lambda = fitness)`. Vectorized.
#'
#' @param fitness numeric `>= 0`, a vector of fitness values.
#'
#' @seealso get_fitness
#' @author Theo Pannetier
#' @export
#' @name draw_nb_offspring_cpp
NULL

draw_nb_offspring_cpp <- function(fitness) {
    .Call('_comrad_draw_nb_offspring_cpp', PACKAGE = 'comrad', fitness)
}

#' Compute the effective population size
#'
#' Computes \code{n_eff}, the effective population size experienced by an
#' individual.
#' @param z numeric vector, the trait values of all individuals in the
#' community.
#' @param comp_width numeric `>= 0`. Width of the competition kernel.
#' @details `n_eff` sums the competitive effects an individual receives from
#' every individual in the community, including the individual itself. It is
#' called effective population size because it is the size of the population
#' that is relevant for competition.
#' @name get_n_eff_cpp
#' @author Thijs Janzen, Théo Pannetier
#' @export
NULL

get_n_eff_cpp <- function(z, comp_width) {
    .Call('_comrad_get_n_eff_cpp', PACKAGE = 'comrad', z, comp_width)
}

