# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Draw a number of offspring given a fitness value
#'
#' The number of offspring is drawn in a Poisson distribution in
#' `rpois(lambda = fitness)`. Vectorized.
#'
#' @param fitness a vector of positive floats, the fitness value(s).
#'
#' @seealso get_fitness
#' @author Theo Pannetier
#' @export
#' @name draw_nb_offspring
#'
NULL

draw_nb_offspring <- function(fitness) {
    .Call('_comrad_draw_nb_offspring', PACKAGE = 'comrad', fitness)
}

#' Sort a vector by ascending value
#'
#' @param x a numeric vector
#'
#' @export
#' @name sort_by_ref
NULL

#' Find gaps in trait values
#'
#' Runs through an ordered vector of trait values, returns the positions of gaps
#' `>= trait_dist_sp` between consecutive values.
#'
#' @param traits a numeric vector, trait values **in ascending order**.
#' @param trait_dist_sp numeric, the minimal trait distance between two
#' clusters of individuals triggering speciation.
#'
#' @author Théo Pannetier
#' @export
#' @name find_trait_gaps
NULL

sort_by_ref <- function(x) {
    invisible(.Call('_comrad_sort_by_ref', PACKAGE = 'comrad', x))
}

find_trait_gaps <- function(traits, trait_dist_sp) {
    .Call('_comrad_find_trait_gaps', PACKAGE = 'comrad', traits, trait_dist_sp)
}

#' Compute the effective population size
NULL

get_n_eff <- function(z, competition_sd, brute_force_opt = "none") {
    .Call('_comrad_get_n_eff', PACKAGE = 'comrad', z, competition_sd, brute_force_opt)
}

simd_size <- function() {
    .Call('_comrad_simd_size', PACKAGE = 'comrad')
}

